apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb
  namespace: flaskapp
data:
  initdb.sql: |
    CREATE DATABASE IF NOT EXISTS flaskdb;
    CREATE USER 'flaskuser'@'%' IDENTIFIED BY 'flaskpass';
    GRANT ALL PRIVILEGES ON flaskdb.* TO 'flaskuser'@'%';
    FLUSH PRIVILEGES;
