apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: flaskapp
spec:
  capacity:
    storage: 256Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/ubuntu/flask-k8s-deployment/mysqldata
